--------------------------------------------------------
--  Fichier créé - vendredi-novembre-05-2021   
--------------------------------------------------------
DROP TABLE "MOUADH"."DEMANDES";
DROP TABLE "MOUADH"."EMPLOYES";
DROP TABLE "MOUADH"."ENTREPRISES";
DROP TABLE "MOUADH"."OFFRES";
--------------------------------------------------------
--  DDL for Table DEMANDES
--------------------------------------------------------

  CREATE TABLE "MOUADH"."DEMANDES" 
   (	"COLUMN1" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM_ENTREPRISE" VARCHAR2(20 BYTE), 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" VARCHAR2(20 BYTE), 
	"ID_ENTREPRISE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "MOUADH"."EMPLOYES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"ID_ENTR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENTREPRISES
--------------------------------------------------------

  CREATE TABLE "MOUADH"."ENTREPRISES" 
   (	"ID_ENTREPRISE" VARCHAR2(20 BYTE), 
	"NUMERO_FIX" VARCHAR2(20 BYTE), 
	"NOM_ENTREPRISE" VARCHAR2(20 BYTE), 
	"COLUMN3" VARCHAR2(20 BYTE), 
	"COLUMN4" VARCHAR2(20 BYTE), 
	"DATE_" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFRES
--------------------------------------------------------

  CREATE TABLE "MOUADH"."OFFRES" 
   (	"NUM_OFFRE" VARCHAR2(20 BYTE), 
	"NUM_FIX" VARCHAR2(20 BYTE), 
	"NOM_ENTREPRISE" VARCHAR2(20 BYTE), 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"ETAT_OFFRE" VARCHAR2(20 BYTE), 
	"DATE_OFFRE" VARCHAR2(20 BYTE), 
	"SALAIRE_ETUDIANT" VARCHAR2(20 BYTE), 
	"ID_ENTREPRISE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MOUADH.DEMANDES
SET DEFINE OFF;
REM INSERTING into MOUADH.EMPLOYES
SET DEFINE OFF;
REM INSERTING into MOUADH.ENTREPRISES
SET DEFINE OFF;
REM INSERTING into MOUADH.OFFRES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index DEMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOUADH"."DEMANDES_PK" ON "MOUADH"."DEMANDES" ("COLUMN1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOUADH"."TABLE1_PK" ON "MOUADH"."EMPLOYES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENTREPRISE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOUADH"."ENTREPRISE_PK" ON "MOUADH"."ENTREPRISES" ("ID_ENTREPRISE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFRES_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOUADH"."OFFRES_PK1" ON "MOUADH"."OFFRES" ("NUM_OFFRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEMANDES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."DEMANDES" ADD CONSTRAINT "DEMANDES_PK" PRIMARY KEY ("COLUMN1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOUADH"."DEMANDES" MODIFY ("COLUMN1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."EMPLOYES" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTREPRISES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."ENTREPRISES" ADD CONSTRAINT "ENTREPRISE_PK" PRIMARY KEY ("ID_ENTREPRISE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("DATE_" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("COLUMN4" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("COLUMN3" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("NOM_ENTREPRISE" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("NUMERO_FIX" NOT NULL ENABLE);
  ALTER TABLE "MOUADH"."ENTREPRISES" MODIFY ("ID_ENTREPRISE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFRES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."OFFRES" ADD CONSTRAINT "OFFRES_PK" PRIMARY KEY ("NUM_OFFRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOUADH"."OFFRES" MODIFY ("NUM_OFFRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEMANDES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."DEMANDES" ADD CONSTRAINT "DEMANDES_FK1" FOREIGN KEY ("ID_ENTREPRISE")
	  REFERENCES "MOUADH"."ENTREPRISES" ("ID_ENTREPRISE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_FK1" FOREIGN KEY ("ID_ENTR")
	  REFERENCES "MOUADH"."ENTREPRISES" ("ID_ENTREPRISE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFRES
--------------------------------------------------------

  ALTER TABLE "MOUADH"."OFFRES" ADD CONSTRAINT "OFFRES_FK1" FOREIGN KEY ("ID_ENTREPRISE")
	  REFERENCES "MOUADH"."ENTREPRISES" ("ID_ENTREPRISE") ENABLE;
